name: Convert Notebooks

on:
  push:
    branches:
      - gh-pages-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Cache dependencies and build outputs to improve workflow execution time
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Convert notebooks
        run: python convert_notebooks.py
      - name: Commit and Push new files to the repository
        uses: scalefreeus/publish-to-github-action@gh-pages-2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'gh-pages-2'
